### ISSUE TITLE
Tracking Issue for Live Migration

### ISSUE THREAD

**Issue by smklein** [oxidecomputer/propolis#81]
Note: this issue is based on https://rfd.shared.oxide.computer/rfd/0071, and likely incomplete.
Please feel free to edit / modify it.

This issue attempts to, at a high-level, capture the necessary work items for LM. Depending on the size of sub-tasks, we can consider splitting out related issues, and dividing ownership.

- [ ] Protocol
  - [ ] Authenticated, encrypted TLS
  - [ ] Versions embedded in structures being transferred. We can start by being extremely selective, requiring exact version match.
- [ ] State Management: Does Propolis' architecture expose necessary interfaces for quiescing, serializing, and transfer of devices?
- [ ] RAM Transfer
  - [ ] Query / Offer dirty pages
  - [ ] Fetch full address space / Xfer full address space
- [ ] CPU Transfer
  - [ ] Registers (general purpose, %rip, %rsp, %rflags, control/segment register, descriptor table, FPU, debug registers, MSRs)
  - [ ] Virtual APIC (ISA-defined registers, timers associated with registers, emulated acceleration (AVIC/APICv state)
  - [ ] Para-virtualized facilities (KVM or hyper-v para-virt clock)
  - [ ] TSC (offset from system VM boot time, frequency)
  - [ ] HVM-specific state (interrupt injection, interrupt windowing, etcs)
- [ ] In-Kernel Emulated Peripherals
  - [ ] PIT (i8254)
  - [ ] PIC (i8259)
  - [ ] IOAPIC
  - [ ] HPET
  - [ ] RTC
  - [ ] ACPI Power Management Timer
- [ ] Miscellaneous Peripherals
  - [ ] Bootroom
  - [ ] Consumer-visible Interfaces
    - [ ] Framebuffer
    - [ ] KB / Mouse
    - [ ] ttya / ttyb
  - [ ]  PCI state (hostbus, bridges)
- [ ] Block Devices
  - [ ] "Pause" message sent to Crucible
  - [ ] Re-inflation of Crucible upstairs on target
- [ ] Network Devices
  - [ ] "Pause" message sent to OPTE
  - [ ] Re-establishment of network traffic through OPTE

Related to https://github.com/oxidecomputer/omicron/issues/252 in Omicron
